### PR TITLE
Add version info to IModMetadata, Change update checks to consider preview versions

### PR DESCRIPTION
**Pull request by danvolchek**
This pull request:
- Adds version status of the mod to `IModMetadata`, so that it can be retrieved by mods as a temporary measure until breaking mod registry changes are made. (#534)
  - This info is interpreted as:
    - If `IModMetadata.UpdateStatus` is null, the update check hasn't happened yet.
    - If `IModMetadata.UpdateStatus.Version` is null and `IModMetadata.UpdateStatus.Error` is null, there are no normal updates.
    - If `IModMetadata.UpdateStatus.Version` is not null, there is a normal update.
    - If `IModMetadata.UpdateStatus.Error` is not null, there was an error checking for a normal update.
  - The same logic applies to `IModMetadata.PreviewUpdateStatus`, but for preview updates.
  - `ModUpdateStatus.Version` and `ModUpdateStatus.Error` will never both be non-null.
- Changes SMAPI's update checking to consider preview versions:
  - If the local version is newer than the remote version but older than the remote preview version, the local version is considered a preview version. Update checking will look for the latest preview or non preview version to update to.
  - Otherwise, update checking will look for the latest non preview version to update to.

I would appreciate comments on how to improve these changes :)

### CODE REVIEW

**Comment by danvolchek** [comment]
I also think an event being fired after update checks are done would be useful. How does something like `<namespace>.UpdateChecksCompleted` sound?

**Comment by Pathoschild** [comment]
@danvolchek We can look into that as part of the new event system (#310), though the existing static events are essentially frozen. I'd prefer to wait until those cover all the basics though, so we have a better idea where to fit it.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 2.6-beta.17, but there are a few issues that are difficult to address with SMAPI's current update-check logic. For example, if a mod has multiple update keys and _any_ of them returned an error, this will set an error for the mod. I'll rewrite the update check logic as part of #551.

**Comment by danvolchek** [comment]
I believe it won't do that - the error is only set if the mod doesn't have a valid update status (all the `mod.UpdateStatus?.Version == null` checks), and setting a working update version should remove any previous errors, but I could be wrong.

I agree that there are other issues, like being unable to determine which update key caused which error, and newer errors overwriting older errors. I'd be happy to help rewriting it if needed :)

**Pull request merged**
