### PR TITLE
API proxy improvements

### PR DESCRIPTION
**Pull request by Shockah**
This PR improves API proxying, implementing:
- Generic arguments in proxied methods
- Default interface implementation proxy methods
- Proxying types in "out" positions (`out` parameters, return value)
- Reverse proxying types in "in" positions (non-`out` non-`ref` parameters)
- Both proxying and reverse proxying types for `ref` parameters
- Unproxying types in "in" positions (if the passed in type was already a known proxy)
- Caching proxied objects (reducing object allocations and also allowing modders to use `object.ReferenceEquals` on those)
- Proxying enums (if their values match)
- Proxying (multi-dimensional) arrays
- Proxying (de/re)constructable types (for example, KeyValuePair, which lets IDictionary work, but also tuples, I guess)
- Proxying delegates

# Potential future improvements:
- Extension method support?

# Example tested code

## API-providing mod side

```cs
public interface ITestOutput
{
    int GetNum();
    string GetText();
    ITestOutput GetParent();
}

public class TestOutput: ITestOutput
{
    private readonly int num;
    private readonly string text;

    public TestOutput(int num = 42, string text = "lulz")
	{
        this.num = num;
        this.text = text;
	}

    public int GetNum()
        => num;

    public string GetText()
        => text;

    public ITestOutput GetParent()
        => this;
}

public interface ITestApi
{
    int NormalMethod(string a, double b, float[] c);

    int DefaultNormalMethod(double b, float[] c)
        => NormalMethod(null, b, c);
}

public class TestApi: ITestApi
{
    public void InputProxyTest(ITestOutput input)
	{
        ProjectFluent.Instance.Monitor.Log($"Received input: {input} | num {input.GetNum()} | text {input.GetText()} | parent {input.GetParent()} | hashcode {input.GetHashCode()} | type {input.GetType().FullName}");
	}

    public int TestProp => 999;

    public string this[string key] {
        get { return key; }
    }

    public ITestOutput GetTestOutput()
        => new TestOutput();

    public void GetTestOutputViaOutParam(out ITestOutput output)
	{
        output = new TestOutput(123, "works");
	}

    public int NormalMethod(string a, double b, float[] c)
        => 42;

    public int MethodWithDefaultValues(object a, int b = 5, string c = "test")
        => b * (c.Length + 1) * (a.GetHashCode() + 1);

    public R GenericMethod<A, B, C, R>(C c, A a, B b)
        => default;

    public int ParamsMethod(int a, params string[] tests)
        => 69;

    public bool OutAndRefMethod(int normalParam, out int outParam, ref int refParam)
    {
        outParam = refParam + normalParam;
        return true;
    }

    public string IsAssignableTest(object anyObj)
        => anyObj.ToString();

    public void Test1(out object a, out object b)
	{
        a = 123;
        b = 545;
    }

    public void Test2(out string a, out string b)
    {
        object aa, bb;
        Test1(out aa, out bb);
        a = aa.ToString();
        b = bb.ToString();
    }

    public void Test3()
	{
        string a, b;
        Test2(out a, out b);
        System.Console.WriteLine(a);
        System.Console.WriteLine(b);
    }
}
```

## API-consuming mod side

```cs
public interface ITestOutput
{
    int GetNum();
    string GetText();
    ITestOutput GetParent();
}

public interface ITestApi
{
    void InputProxyTest(ITestOutput input);

    int TestProp { get; }

    string this[string key] { get; }

    ITestOutput GetTestOutput();

    void GetTestOutputViaOutParam(out ITestOutput output);

    int NormalMethod(string a, double b, float[] c);

    int DefaultNormalMethod(double b, float[] c);

    int MethodWithDefaultValues(object a, int b = 5, string c = "test");

    R GenericMethod<A, B, C, R>(C c, A a, B b);

    int ParamsMethod(int a, params string[] tests);

    bool OutAndRefMethod(int normalParam, out int outParam, ref int refParam);

    object IsAssignableTest(string anyObj);
}

public class CustomTestOutput: ITestOutput
{
    public int GetNum()
        => 666;

    public string GetText()
        => "custom";

    public ITestOutput GetParent()
        => null;
}
```

## API-consuming mod usage

```cs
var testApi = Helper.ModRegistry.GetApi<ITestApi>("Shockah.ProjectFluent");
int outInt;
int refInt = 3;

Monitor.Log($"NormalMethod: {testApi.NormalMethod("a", 3.14, new float[] { 2.3f, 5.7f, 11.13f })}");
Monitor.Log($"DefaultNormalMethod: {testApi.DefaultNormalMethod(3.14, new float[] { 1, 2, 3 })}");
Monitor.Log($"MethodWithDefaultValues: {testApi.MethodWithDefaultValues("asdf")}");
Monitor.Log($"GenericMethod: {testApi.GenericMethod<int, float, double, string>(3.0, 1, 2f)}");
Monitor.Log($"ParamsMethod: {testApi.ParamsMethod(10, "a", "b", "c")}");
Monitor.Log($"OutAndRefMethod: {testApi.OutAndRefMethod(2, out outInt, ref refInt)}");
Monitor.Log($"IsAssignableTest: {testApi.IsAssignableTest("testing")}");
Monitor.Log($"outInt: {outInt}");

ITestOutput testOutput = testApi.GetTestOutput();
Monitor.Log($"{testOutput}");
Monitor.Log($"{testOutput.GetNum()}");
Monitor.Log($"{testOutput.GetText()}");
Monitor.Log($"{testOutput.GetParent() == null}");

ITestOutput testOutput2;
testApi.GetTestOutputViaOutParam(out testOutput2);
Monitor.Log($"{testOutput2}");
Monitor.Log($"{testOutput2.GetNum()}");
Monitor.Log($"{testOutput2.GetText()}");
Monitor.Log($"{testOutput2.GetParent() == null}");

Monitor.Log($"ReferenceEquals: {object.ReferenceEquals(testOutput, testOutput.GetParent())}");
Monitor.Log($"TestProp: {testApi.TestProp}");
Monitor.Log($"Indexer: {testApi["asdf"]}");

testApi.InputProxyTest(testOutput);
testApi.InputProxyTest(new CustomTestOutput());
```

## Log after above example

```
[17:08:37 TRACE Predictable Retaining Soil] Accessed mod-provided API for Project Fluent.
[17:08:37 TRACE Predictable Retaining Soil] NormalMethod: 42
[17:08:37 TRACE Predictable Retaining Soil] DefaultNormalMethod: 42
[17:08:37 TRACE Predictable Retaining Soil] MethodWithDefaultValues: -1847822765
[17:08:37 TRACE Predictable Retaining Soil] GenericMethod:
[17:08:37 TRACE Predictable Retaining Soil] ParamsMethod: 69
[17:08:37 TRACE Predictable Retaining Soil] OutAndRefMethod: True
[17:08:37 TRACE Predictable Retaining Soil] IsAssignableTest: testing
[17:08:37 TRACE Predictable Retaining Soil] outInt: 5
[17:08:37 TRACE Predictable Retaining Soil] StardewModdingAPI.Proxies.From<Shockah.PredictableRetainingSoil_Shockah.PredictableRetainingSoil.APIs.ITestOutput>_To<Shockah.ProjectFluent_Shockah.ProjectFluent.ITestOutput>
[17:08:37 TRACE Predictable Retaining Soil] 42
[17:08:37 TRACE Predictable Retaining Soil] lulz
[17:08:37 TRACE Predictable Retaining Soil] False
[17:08:37 TRACE Predictable Retaining Soil] StardewModdingAPI.Proxies.From<Shockah.PredictableRetainingSoil_Shockah.PredictableRetainingSoil.APIs.ITestOutput>_To<Shockah.ProjectFluent_Shockah.ProjectFluent.ITestOutput>
[17:08:37 TRACE Predictable Retaining Soil] 123
[17:08:37 TRACE Predictable Retaining Soil] works
[17:08:37 TRACE Predictable Retaining Soil] False
[17:08:37 TRACE Predictable Retaining Soil] ReferenceEquals: True
[17:08:37 TRACE Predictable Retaining Soil] TestProp: 999
[17:08:37 TRACE Predictable Retaining Soil] Indexer: asdf
[17:08:37 TRACE Project Fluent] Received input: Shockah.ProjectFluent.TestOutput | num 42 | text lulz | parent Shockah.ProjectFluent.TestOutput | hashcode 34903833 | type Shockah.ProjectFluent.TestOutput
[17:08:37 TRACE Project Fluent] Received input: StardewModdingAPI.Proxies.From<Shockah.PredictableRetainingSoil_Shockah.ProjectFluent.ITestOutput>_To<Shockah.ProjectFluent_Shockah.PredictableRetainingSoil.APIs.ITestOutput> | num 666 | text custom | parent  | hashcode 10423942 | type StardewModdingAPI.Proxies.From<Shockah.PredictableRetainingSoil_Shockah.ProjectFluent.ITestOutput>_To<Shockah.ProjectFluent_Shockah.PredictableRetainingSoil.APIs.ITestOutput>
```

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks for all the work! I have two main concerns though:

1. This makes type proxying directly available to mods. It's an internal implementation detail though, it's not meant to be part of the public API and there's no guarantee SMAPI will always use that approach.
2. This triples the amount of code for the proxying. The proxying is just a small part of the modding API to support mod integrations, SMAPI isn't meant to be a full-featured proxying library.

If we can't use an existing proxying library (maybe something like [Castle DynamicProxy](http://www.castleproject.org/projects/dynamicproxy/)?), this seems like something that'd be more suitable as its own NuGet package which SMAPI could possibly reference.

**Comment by Shockah** [comment]
@Pathoschild 

> 1. This makes type proxying directly available to mods. It's an internal implementation detail though, it's not meant to be part of the public API and there's no guarantee SMAPI will always use that approach.

If you meant the `TryProxy` method, it's meant to be a replacement for the lack of the ability to use `is` type checking and type casting when using proxied types. I think it's the very least we can do to support such use cases, and the public API should be extended to allow this.

> 2. This triples the amount of code for the proxying. The proxying is just a small part of the modding API to support mod integrations, SMAPI isn't meant to be a full-featured proxying library.

> If we can't use an existing proxying library (maybe something like [Castle DynamicProxy](http://www.castleproject.org/projects/dynamicproxy/)?), this seems like something that'd be more suitable as its own NuGet package which SMAPI could possibly reference.

I looked for some duck-typing/proxying libraries for .NET, but my google-fu didn't help me this one time, and I didn't even find the Castle DynamicProxy library.
Briefly looked into it. It looks like the library is meant to be a one-way proxy - making sure the consuming side is completely unaware of any proxying to be happening. I don't believe this is something we want to do here - sometimes our users have to be *aware* this happens.
Also, I *don't think* they have a way of unproxying the object? Which means that not only we'd have to double-proxy an object, but also that you don't get the same object you hoped to get back on the providing side.

I'm moving the proxying API into a separate library, while also cleaning it up to be completely unrelated to SMAPI, but including such a dependency sounds like a major (and possibly breaking?) change to mods, and I'd like at least some of the changes to be already available to mods (mostly my upcoming Project Fluent).
I propose for `TryProxy` to be removed (for now) to keep the existing public API unchanged, and later on for the library to be incorporated and maybe then for `TryProxy` to be re-added in some way. This should allow to keep the same API mods currently use to trigger proxying in-tact.

**Comment by Shockah** [comment]
I started work on a separate library, using mostly the code from current SMAPI code and this PR, but cleaned up to be SMAPI-independent. It should be working fine, but I still have to add unit tests, re-add code documentation, add some usage documentation and make it available as a NuGet. Obviously I will credit SMAPI before publishing the package.

I assume the Apache 2.0 license is fine for use in SMAPI?

https://github.com/Nanoray-pl/Pintail/tree/develop

**Comment by Shockah** [comment]
I think the code of the library itself is mostly done, including any XML docs and some unit tests. I've published the package on NuGet.
https://www.nuget.org/packages/Pintail/

I guess since nothing changed regarding this PR, I'll just get to updating it by using the newly-published package as a reference.

**Comment by Pathoschild** [comment]
I'm away on vacation for a few days, but here's some quick answers so you're not kept waiting.

> [`TryProxy` is] meant to be a replacement for the lack of the ability to use `is` type checking and type casting when using proxied types. I think it's the very least we can do to support such use cases, and the public API should be extended to allow this.

`GetApi()` without type arguments will return the unproxied API instance, which you can use for `is` matching or type checks/casting. If you need to try matching the API against multiple proxy interfaces, you can call `GetApi<T>()` for each type and use the one that succeeds.

Otherwise SMAPI isn't a proxying library, and the only guarantee when calling `GetApi<T>()` is that (if it succeeds) you'll have an API of type `T` you can call. If you really need full arbitrary proxying/unproxying support for your mod, the benefit of a separate library is that your mod can call it directly.


> It looks like the library is meant to be a one-way proxy - making sure the consuming side is completely unaware of any proxying to be happening. I don't believe this is something we want to do here - sometimes our users have to be _aware_ this happens.

That's the same philosophy SMAPI uses. The proxying is an implementation detail, and `GetApi<T>()` doesn't always use proxying (e.g. if the API can be cast instead).


> I'm moving the proxying API into a separate library [...] but including such a dependency sounds like a major (and possibly breaking?) change to mods, and I'd like at least some of the changes to be already available to mods (mostly my upcoming Project Fluent).

SMAPI manages its own dependencies independently of mods, so adding a new dependency that's not directly exposed through the public API won't have any effect on mods. If you need direct access to the library, you can always just reference the DLL in the game's `smapi-internal` folder (which is how mods use Harmony for example).


> I propose for `TryProxy` to be removed (for now) to keep the existing public API unchanged, and later on for the library to be incorporated and maybe then for `TryProxy` to be re-added in some way. This should allow to keep the same API mods currently use to trigger proxying in-tact.

SMAPI is just the mod loader and modding API, it's not meant to have random utilities. Proxying is an implementation detail of how mod APIs work, and I don't have any current plans to add proxying as a public mod API.

> I assume the Apache 2.0 license is fine for use in SMAPI?

There are two issues:
* Any code you took from SMAPI is LGPL and can't necessarily be relicensed. I _think_ I'm the only contributor to that code, but I'll need to check when I'm back from vacation. If I am, then I'd be fine relicensing any code you need to use if needed, as long as attribution is maintained.
* SMAPI ideally shouldn't depend on libraries with more restrictive licenses, since that effectively changes the license to the union of all its dependencies' restrictions. So the ideal license would be LGPL to match SMAPI, or a more permissive license like MIT.

**Comment by Shockah** [comment]
I'm aware there are other ways of handling this, potentially by requiring other mods' projects to reference my mod's DLL, but the current API proxying is *the* way that seems to be preferred, which is why I tried to "improve" it, allowing for much more complexity and feeling more like using real C#, instead of being super-limited by the types visible on both mod sides (providing mod, and consuming mod). I'd say this would greatly benefit not only me, but other modders too (I've seen some interest in better proxying from others on the Discord server). But if you think there is no place in SMAPI for this, then I guess I'll just drop the proxying library project (and hide it on NuGet), and go back to requiring actual DLL references. I just wish it was communicated better much earlier.

Regarding licensing, yeaaah, I guess I shouldn't have taken anything from SMAPI itself, but to be honest compared to what is currently in the repository there is barely any resemblance after all of my changes.
Also, I was under impression the Apache 2.0 license is pretty much the same as MIT, but has some additional wording regarding patents? Meaning it should be pretty permissive.
Not that any of those points matter now.

Also, yep, I remembered you were supposed to be away in the next few days! Rest well! I could have waited until you're back, no worries. After all I'm also getting scolded by my partner that I should be spending time with them instead of coding, hah.

**Comment by Pathoschild** [comment]
Yeah, I think there was a bit of miscommunication, sorry! I thought you were working on improvements to the transparent proxying to support more types, not adding a new API. It seems like the library would still be useful for improving the transparent proxying, but up to you!

**Comment by Shockah** [comment]
Well, like I mentioned, the `TryProxy` method isn't really that big of a deal, and I don't mind it not becoming part of the API. I only really added it, because I felt it was needed for completeness' sake.

Other than that one method, everything else is just transparent to any users of `GetApi`.

Okay, I'll try to rework this PR to instead reference my library (assuming you're okay with the licensing; if Apache 2.0 is still a no-go, I could make it a one-off MIT - it's just that I use Apache 2.0 on pretty much all of my repositories) and make all of those changes an implementation detail - `GetApi` will stay unchanged, and no new API will be added.

We can talk about this more after you're back. Again, rest well!

**Comment by Shockah** [comment]
So, like I mentioned earlier - I've converted this to a standalone library and made some heavy changes... and now the proxying works for pretty much anything I could think of. Normal parameters, outs, refs, arrays (okay, I just remembered multidimensional arrays probably don't work, but that's not high priority, and I can always make an update to the lib)... Enums (if their values match)... Types with a matching Deconstruct method and a constructor...
All of those changes led to even this thing working: `IDictionary<StateEnum, ISet<IApiResult>>`.
Also, I've removed the TryProxy method from SMAPI's API (but it's still part of the library - mods would have a hard time getting to it, it's doable via reflection, but there shouldn't be a need anymore, considering most proxy types "just work"™). This means this PR no longer touches the public API.

You can see all of the tests I've written for the lib here: https://github.com/Nanoray-pl/Pintail/tree/master/PintailTests.
This PR now removes all types related to proxying from SMAPI and uses Pintail instead. I've tested this to be working with existing mods which make use of the currently existing proxying, and the APIs they use are functioning properly:
```
[19:07:14 INFO  SMAPI] Loaded 15 mods:
[19:07:14 INFO  SMAPI]    CJB Cheats Menu 1.29.3 by CJBok and Pathoschild | Simple in-game cheats menu!
[19:07:14 INFO  SMAPI]    CJB Item Spawner 2.1.5 by CJBok and Pathoschild | Simple in-game item spawner!
[19:07:14 INFO  SMAPI]    Console Commands 3.13.4 by SMAPI | Adds SMAPI console commands that let you manipulate the game.
[19:07:14 INFO  SMAPI]    Content Patcher 1.24.8 by Pathoschild | Loads content packs which edit game data, images, and maps without changing the game files.
[19:07:14 INFO  SMAPI]    Content Patcher Animations 1.2.2 by spacechase0 | Lets Content Patcher packs animate textures.
[19:07:14 INFO  SMAPI]    Don't Stop Me Now 1.0.1 by Shockah | No more stopping for any actions.
[19:07:14 INFO  SMAPI]    Error Handler 3.13.4 by SMAPI | Handles some common vanilla errors to log more useful info or avoid breaking the game.
[19:07:14 INFO  SMAPI]    Flexible Sprinklers 1.1.2 by Shockah | Makes the sprinklers more flexible, while keeping their behavior the same under perfect conditions.
[19:07:14 INFO  SMAPI]    Generic Mod Config Menu 1.8.1 by spacechase0 | Adds an in-game UI to edit other mods' config options (for mods which support it).
[19:07:14 INFO  SMAPI]    Predictable Retaining Soil 1.1.0 by Shockah | Makes all retaining soils stay watered a specified number of days (instead of being random).
[19:07:14 INFO  SMAPI]    Prismatic Tools 1.7.1-unofficial.9-pathoschild by stokastic | Adds prismatic tools and sprinklers to the game.
[19:07:14 INFO  SMAPI]    Project Fluent 1.0.0 by Shockah | A modern localization/translation framework.
[19:07:14 INFO  SMAPI]    Save Backup 3.13.4 by SMAPI | Automatically backs up all your saves once per day into its folder.
[19:07:14 INFO  SMAPI]    Skip Intro 1.9.6 by Pathoschild | Skips the game's loading intro.
[19:07:14 INFO  SMAPI]    SpaceCore 1.8.1 by spacechase0 | A framework mod used by some of my other mods.
```
Please take a look at the library, do any additional tests you deem required and keep me informed.

EDIT: I've just tried to use this modified SMAPI with my current multiplayer playthrough mod set, and it was throwing exceptions in my code... so I'll have to look at it again.

EDIT2: It was a stupid issue on my side, fixed it. This is a full log of the above mod set that is now working great. https://smapi.io/log/7aaf5d32ba47479eae84bb0e54469227

**Comment by Shockah** [comment]
Yet another update. Delegate proxying is now a thing too.
Just in case, attached a log for a working copy of a game with the same set of mods as above: https://smapi.io/log/52338758e3dc429a8cfa523720bcd051

**Comment by Shockah** [comment]
Yet another update, multi-dimensional arrays are now supported.

**Comment by Shockah** [comment]
I went ahead and started implementing Project Fluent’s API and using it in a mod of mine on a custom SMAPI build with these changes. Unfortunately, apparently there are still some problems and I’m getting an exception when retrieving the API. I can’t look into it until tomorrow evening (so, like, 18 hours from now at least), so I thought I’d at least let you know.
Existing mods are functioning with no problems, I just had a 2 hour multiplayer session on this custom build without any issues.

**Comment by Shockah** [comment]
Fixed the exception mentioned above, the below mod API is now functional and works fine when called from another mod.
```cs
using StardewModdingAPI;
using StardewValley;
using StardewValley.GameData;

namespace Shockah.ProjectFluent
{
	public interface IFluentApi
	{
		IGameLocale CurrentLocale { get; }

		IGameLocale GetBuiltInLocale(LocalizedContentManager.LanguageCode languageCode);
		IGameLocale GetModLocale(ModLanguage language);

		IFluent<Key> GetLocalizations<Key>(IGameLocale locale, IManifest mod, string name = null);
		IFluent<Key> GetLocalizationsForCurrentLocale<Key>(IManifest mod, string name = null);
	}
}
```

**Comment by Pathoschild** [comment]
This looks pretty good! I like how methods still call the underlying implementation directly without further proxying when possible, like the old SMAPI code. Here's a few suggestions, though they're not all blockers for SMAPI.

## Suggestions
### Optimizations
* SMAPI's implementation didn't create a proxy at all if the API type was already compatible. That happens often with SMAPI's use case, since a mod might have a direct assembly reference on a required dependency and use the actual interface provided by the other mod. Pintail always creates a proxy regardless.
* `Nothing.AtAll` creates a new instance every time it's called. If that's not intended, you can change `static Nothing AtAll => new()` to `static Nothing AtAll { get; } = new()` to avoid it.
* Marking `Nothing` as `readonly struct` would enable some compiler optimizations.

### General API
* An `IProxyManager` which wraps `IProxyManager<Nothing>` would simplify code like this:
   ```cs
   // current
   IModApi api = factory.ObtainProxy<Nothing, IModApi>(implementation, Nothing.AtAll, Nothing.AtAll);

   // suggested
   IModApi api = factory.ObtainProxy<IModApi>(implementation);
   ```
* Pintail uses interfaces with `Default*` implementations, which suggests it's supposed to allow swapping in our own implementations. However the underlying code has logic like `this.Manager.ObtainProxyFactory(actualProxyInfo) as DefaultArrayProxyFactory<Context>`, which will fail if the implementations are changed.

### Generated code
* In .NET 5, the name passed into the `ModuleBuilder` constructor is ignored and it's always called something like `RefEmit_InMemoryManifestModule`. I suggest using `assemblyBuilder.GetName().Name` in the proxy type names instead. (That doesn't affect SMAPI though, since it'll override the type name provider.)

### Documentation
* The [public readme](https://github.com/Nanoray-pl/Pintail#readme) should ideally have more info for long-term project health. I suggest something like [this readme](https://github.com/Pathoschild/FluentHttpClient#readme) (e.g. brief description of what the package does, install steps, basic and advanced usage, supported features, etc).
* It's not clear what the context does or what benefits it provides over passing `Nothing`. Looks like it allows passing custom info to the callbacks like `typeNameProvider`?

**Comment by Shockah** [comment]
> SMAPI's implementation didn't create a proxy at all if the API type was already compatible. That happens often with SMAPI's use case, since a mod might have a direct assembly reference on a required dependency and use the actual interface provided by the other mod. Pintail always creates a proxy regardless.

I'd say if you're calling ObtainProxy, then you *want* a proxy. This way it potentially opens the way for some related functionality, like wrapping the original call with your own code. In the context of what we're doing here though, if your type was already compatible, why were you calling it to begin with? Also, I believe SMAPI already makes that check before proxying anyway?

> `Nothing.AtAll` creates a new instance every time it's called. If that's not intended, you can change `static Nothing AtAll => new()` to `static Nothing AtAll { get; } = new()` to avoid it.

Yep, that wasn't intended. I will change it, but it shouldn't be affecting SMAPI either, as we're using `string` contexts here (unique mod IDs).

> An `IProxyManager` which wraps `IProxyManager<Nothing>` would simplify code

This is currently handled via extension methods with generic type constraints, as I didn't want to introduce another type.

> Pintail uses interfaces with `Default*` implementations, which suggests it's supposed to allow swapping in our own implementations. However the underlying code has logic like `this.Manager.ObtainProxyFactory(actualProxyInfo) as DefaultArrayProxyFactory<Context>`, which will fail if the implementations are changed.

I didn't really know how to name it otherwise (just `ProxyManager` and `ProxyFactory`? `Proxy[Manager/Factory]Impl`?), and in theory you *could* write a custom Manager and a set of Factories for it.
I'm also not exactly happy with the mentioned `DefaultArrayProxyFactory` cast, but I couldn't exactly think of a better way of handling this specific case. If you have an idea, please give me a shout, as I'd also like to make those *actually* independent.

> In .NET 5, the name passed into the `ModuleBuilder` constructor is ignored and it's always called something like `RefEmit_InMemoryManifestModule`. I suggest using `assemblyBuilder.GetName().Name` in the proxy type names instead. (That doesn't affect SMAPI though, since it'll override the type name provider.)

Okay, will change that one.
Regarding overriding the type name provider in SMAPI - I'm not sure it's that great of an idea. I assume you've seen the default one uses MD5 hashes for type names. This is done on purpose. The proxy type names were getting so ridiculously long, that they went over the limit (which seems to be 1024 characters), and it was failing to build a type with such a name. This sounds crazy on paper and you would think "who the hell would create such a complex hierarchy", but just having an `IDictionary` parameter (or was it `IDictionary` with another interface to proxy as the key and/or value?) makes it do that.
At that point I was spending too much time on the lib, so I just went with MD5, but if you can think of a better naming scheme, I'd gladly add it and make it the default.

> The [public readme](https://github.com/Nanoray-pl/Pintail#readme) should ideally have more info for long-term project health.

Yep, I agree with that one, but that can be done later, and I was also waiting for your feedback, so I can have some functionality and APIs set in stone first.

> It's not clear what the context does or what benefits it provides over passing `Nothing`. Looks like it allows passing custom info to the callbacks like `typeNameProvider`?

Yep, that's one thing it does. The other thing is differentiating between proxy factories for different "contexts" (which in our case would be mods and their unique IDs). Current SMAPI code used unique mod IDs as part of a key used for storing the proxy factory instance (or, well, builders, if we're talking pre-PR code). I wanted to keep this behavior, so different mods will always get different proxy factory instances (and in turn different proxy objects too).

**Comment by Pathoschild** [comment]
> I didn't really know how to name it otherwise (just `ProxyManager` and `ProxyFactory`? `Proxy[Manager/Factory]Impl`?), and in theory you *could* write a custom Manager and a set of Factories for it.

I think you can just drop the `Default` prefix. Especially since it's the main entry point to your library, so it implies there are non-default implementations available. That doesn't affect this PR though.

> Regarding overriding the type name provider in SMAPI - I'm not sure it's that great of an idea. [...] The proxy type names were getting so ridiculously long, that they went over the limit (which seems to be 1024 characters), and it was failing to build a type with such a name.

For SMAPI's purposes, I mainly just want to be able to identify which API is failing in error stack traces. One option might be to allow customizing the namespace when we obtain a proxy, so the types would look like `StardewModdingAPI.Proxies.From<ImplementationName>_To<InterfaceName>.GeneratedTypeName`?

> Yep, I agree with that one, but that can be done later, and I was also waiting for your feedback, so I can have some functionality and APIs set in stone first.

I'm fine either way. I often start with the docs though, since needing to explain how to use something is a quick way to spot any limitations/complications in the design.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 3.14.0. Thanks for the help!

**Pull request merged**
