### PR TITLE
Add config schema generation

### LINKED ISSUE #928: Generate `config.schema.json` file for validation inside mod managers
SMAPI mods write `config.json` files into the mod folder. This is the usual modding process:

```mermaid
flowchart TD
    1[Install mod]
    2[Run game to generate config.json]
    3[Edit config.json]
    4[Run Game]
    5{Valid config?}
    1 --> 2 --> 3 --> 4 --> 5
    5 -- Yes --> Done
    5 -- No --> 3
```

To make modding easier and less error-prone, mod managers should be able to validate the `config.json` file without requiring the user to run the game and check the SMAPI logs:

```mermaid
flowchart TD
    1[Install mod]
    2[Run game to generate config.json]
    3[Edit config.json]
    5{Valid config?}
    1 --> 2 --> 3 --> 5
    5 -- Yes --> Done
    5 -- No --> 3
```

Currently, mod managers are only able to validate if the `config.json` file is valid JSON. For validation of properties, mod managers would need a JSON schema file `config.schema.json`. Such a file could be generated by SMAPI on startup.

Besides validation, a schema file would also allow mod managers to provide rich config editors without requiring users to open external tools like Notepad++ or VS Code. This makes modding even easier and will massively reduce support questions for broken config files.

### PR DESCRIPTION
**Pull request by erri120**
Resolves #928.

## Changes

- Adds a new dependency to `SMAPI.Toolkit`: `NJsonSchema` for schema generation.
- Adds `GenerateConfigSchema` option to `SConfig` that's set to `false` by default.
- Adds `IDataHelper.WriteJsonSchemaFile` and `JsonHelper.WriteJsonSchemaFile` to generate and write the schema to file.
- Updates `ModHelper.ReadConfig` to generate the file `config.schema.json`.

## Notes

I think `develop` references DLLs from Stardew Valley 1.6 that I don't have access with, so I had to create the code on `stable` and port it to `develop`.

I'm not sure how to test this PR, there aren't any unit tests that I can run. I thought about installing latest SMAPI normally and just overwriting the DLLs in the game folder with the ones I build using the PR. However, I don't even know if that works with the .NET DLL resolution process...

### CODE REVIEW

**Comment by Shockah** [comment]
You'd be correct in saying that `develop` references Stardew Valley 1.6. Getting access is as simple as joining the Stardew Valley Discord server and asking in the `#making-mods` channel to get added (not even pinging anyone - anyone already in the alpha can add you).

**Comment by Pathoschild** [comment]
Thanks! Unfortunately [Json.NET Schema isn't free](https://www.newtonsoft.com/store/jsonschema), and the AGPL version is limited to 1000 validations per hour. That could easily be reached in our case (since players can have hundreds or thousands of mods, they may launch the game more than once per hour, and mods often read/write their config files more than once).

>

**Comment by erri120** [comment]
Updated PR to use NJsonSchema.

**Comment by Pathoschild** [comment]
Unfortunately NJsonSchema fails for many mods ([see log](https://smapi.io/log/2aa84d8f9be84530910be014d8e3cf6f)). A few sample cases:

mod | config | result
--- | ------ | ------
[Automate](https://www.nexusmods.com/stardewvalley/mods/1063) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/Automate/Framework/Models/ModConfig.cs) | ❌ [crashes with `InvalidOperationException`](https://github.com/Pathoschild/SMAPI/assets/230581/9eaebb64-e28d-412b-9e84-381e6abb189a).
[Chests Anywhere](https://www.nexusmods.com/stardewvalley/mods/518) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/Framework/ModConfig.cs) | ❌ ditto Automate.
[CJB Cheats Menu](https://www.nexusmods.com/stardewvalley/mods/4) | [config](https://github.com/CJBok/SDV-Mods/blob/master/CJBCheatsMenu/Framework/Models/ModConfig.cs) | ❌ ditto Automate.
[CJB Item Spawner](https://www.nexusmods.com/stardewvalley/mods/93) | [config](https://github.com/CJBok/SDV-Mods/blob/master/CJBItemSpawner/Framework/Models/ModConfig.cs) | ❌ ditto Automate.
[CJB Show Item Sell Price](https://www.nexusmods.com/stardewvalley/mods/5) | [config](https://github.com/CJBok/SDV-Mods/blob/master/CJBItemSpawner/Framework/Models/ModConfig.cs) | ❌ creates a schema for an empty object: `{ "$schema": "...", title: "ModConfig", type: "object", "additionalProperties": false }`.
[Content Patcher](https://www.nexusmods.com/stardewvalley/mods/1915) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/Framework/ConfigModels/ModConfig.cs) | ❌ ditto Automate.
[Crops Anytime Anywhere](https://www.nexusmods.com/stardewvalley/mods/3000) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/CropsAnytimeAnywhere/Framework/ModConfig.cs) | ✅ Seems correct.
[Data Layers](https://www.nexusmods.com/stardewvalley/mods/1691) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/Framework/ModConfig.cs) | ❌ ditto Automate.
[Debug Mode](https://www.nexusmods.com/stardewvalley/mods/679) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/Framework/ModConfig.cs) | ❌ ditto Automate.
[Fast Animations](https://www.nexusmods.com/stardewvalley/mods/1089) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/FastAnimations/Framework/ModConfig.cs) | ✅ Seems correct.
[Generic Mod Config Menu](https://www.nexusmods.com/stardewvalley/mods/5098) | [config](https://github.com/spacechase0/StardewValleyMods/blob/develop/GenericModConfigMenu/Framework/OwnModConfig.cs) | ❌ only includes `ScrollSpeed` property.
[Horse Flute Anywhere](https://www.nexusmods.com/stardewvalley/mods/7500) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/HorseFluteAnywhere/Framework/ModConfig.cs) | ❌ ditto Automate.
[NPC Location Compass](https://www.nexusmods.com/stardewvalley/mods/3045) | [config](https://github.com/Bouhm/stardew-valley-mods/blob/main/LocationCompass/Framework/ModConfig.cs) | ✅ Seems correct.
[Skip Intro](https://www.nexusmods.com/stardewvalley/mods/533) | [config](https://github.com/Pathoschild/StardewMods/blob/develop/SkipIntro/Framework/ModConfig.cs) | ✅ Seems correct.

It seems to only work with properties (not fields), and fails with some common types like [`KeybindList`](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/Utilities/KeybindList.cs) (maybe due to the get-only properties?).

I rebased the PR branch onto the latest `develop`, so you can try it like this:
1. Reset to the latest PR branch.
2. Open SMAPI in Visual Studio.
3. In `SMAPI/Constants.cs`, change the `MinimumGameVersion` back to 1.6.8.
4. Click _Build > Rebuild Solution_ to deploy the SMAPI files.
5. Click _Debug > Start Without Debugging_ to launch SMAPI.

**Comment by Pathoschild** [comment]
I'll close this as _won't do_ per the above, but feel free to submit a new PR if you can get NJsonSchema or another package to work. Thanks for the help!

**Pull request closed without merging**
