### PR TITLE
Add overload to the player_add console command to add items by name

### PR DESCRIPTION
**Pull request by danvolchek**
This PR modifies the player_add command to effectively allow `<type> <id>` to be replaced with `<name>`. Items are looked up by name if the first argument to the command is not an `ItemType`. When looking up items by name, the command only succeeds if there is exactly one such item across all `ItemType`s.

Some things to consider:
  - I compared with the Item's `DisplayName` only. Would users ever want to compare with SDV's internal name?
  - I added error output which I think is clear, but the usage description change may not be so clear.
  - As a hacky way to support adding an item with spaces in its name, when looking up an item by name underscores are replaced with spaces. As of now this is undocumented and will conflict if any in game items actually have underscores in their name. Maybe this should just be removed entirely.

Feel free to comment and ask for changes.

### CODE REVIEW

**Comment by Pathoschild** [comment]
I'm not fond of the underscore since it's nonstandard, and I'd want to minimise ambiguity in the commands (e.g. if `<type>` isn't valid, did they make a mistake or are they searching by name?).

How about overloading `<type>` with a `name` value and supporting quoted names?
```
player_add item 433 10
player_add name "Coffee Bean" 10
```

If the search matches multiple values (or one non-exact match), we should show a helpful response:
```
player_add name "Sword"

Found multiple item names containing 'Sword'. Type one of these commands for the one you want:

type   | name                | command
------ | ------------------- | ---------------------
Object | Ancient Sword       | player_add object 109
Weapon | Bone Sword          | player_add weapon 5
Weapon | Dark Sword          | player_add weapon 2
Weapon | Forest Sword        | player_add weapon 15
Weapon | Galaxy Sword        | player_add weapon 4
Weapon | Pirate's Sword      | player_add weapon 43
Weapon | Rusty Sword         | player_add weapon 0
Weapon | Steel Smallsword    | player_add weapon 11
Weapon | Tempered Broadsword | player_add weapon 52
```

**Comment by danvolchek** [comment]
Regarding the player_add command:
  - I added a world ready context check, since you can't add items to your inventory if a save is not loaded.
  - I've changed it to how you mentioned, with Name being a new option for type. This is a good idea :)
  - A name will match if there is an exact match, regardless of any other non-exact matches. Any other case (i.e. no matches, or one non-exact or many non-exact matches) prints helpful error info.
  - In the case of many non-exact matches, I print the table at `LogLevel.Info` because for lots of items, it results in a large sea of red at `LogLevel.Error`. Do we still want to use `LogLevel.Error`?

Regarding support for quoted names:

How exactly do you want to approach this? I was able to come up with a prototype that modifies `CommandManager.Trigger(string)`. It makes sense most of the time, but some edge cases could be not desirable. For example, both `"input"other` and `"input" other` are treated as `[input, other]`. I haven't commit these changes so we can talk more about it on the discord.

**Comment by Pathoschild** [comment]
I think the way bash handles it makes sense: if you end the quote inside a word, the argument extends to the end of that word.
```
for arg in before "x y"z after; do echo $arg; done

> before
> x yz
> after
```

**Comment by danvolchek** [comment]
I've added quoted string support for console commands.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 2.6. Thanks!

**Pull request merged**
