### PR TITLE
Add trainer commands: player_addwallpaper and player_addflooring

### PR DESCRIPTION
**Pull request by spacechase0**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! I was thinking of creating two commands to handle all item types, so you could search them all like this:

```
> list_items red

type      | id   | name
--------- | ---- | -------------------
fish      | 146  | Red Mullet
fish      | 150  | Red Snapper
furniture | 12   | Red Diner Chair
furniture | 294  | Red Armchair
furniture | 424  | Red Couch
furniture | 1296 | Manicured Pine
furniture | 1451 | Red Rug
furniture | 1618 | Red Cottage Rug
object    | 146  | Red Mullet
object    | 150  | Red Snapper
object    | 230  | Red Plate
object    | 266  | Red Cabbage
object    | 331  | Weathered Floor
object    | 420  | Red Mushroom
object    | 437  | Red Slime Egg
object    | 485  | Red Cabbage Seeds
weapon    | 52   | Tempered Broadsword
```

Then you could add any item like this:
```
> player_additem 485
OK, added Red Cabbage Seeds to your inventory.

> player_additem fish 146
OK, added Red Mullet to your inventory.

> player_additem wallpaper 7
OK, added wallpaper #7 to your inventory.
```

I don't think the game has any names or descriptions for wallpaper, though. I guess we could just list them like this:
```
type      | id    | name
--------- | ----- | -------------------
flooring  | 0-39  | Flooring
wallpaper | 0-111 | Wallpaper
```

What do you think of that idea?

**Comment by spacechase0** [comment]
That looks good. It seems a bit odd not having to specify the type for `object`, but it makes sense since that would be what is used in the majority of cases.

**Comment by Pathoschild** [comment]
Yep. `player_additem object 485` would work too, though.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming version. (I'll merge the commands as part of that release.) Thanks!

**Pull request merged**
