### PR TITLE
Added code to suppress mouse clicks

### LINKED ISSUE #384: EventArgsInput.SuppressButton doesn't suppress mouse clicks
Currently SuppressButton is rolling back keyboard presses and controller inputs, but is not rolling back mouse buttons.

### PR DESCRIPTION
**Pull request by YonKuma**
closes Pathoschild/SMAPI#384

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! Instead of converting to an input button and then checking `MouseLeft` and `MouseRight`, you can do this:
```cs
else if (this.Button == SButton.MouseLeft)
```

Not related to your pull request, but that method has a pretty significant bug: it uses `this.Button` and ignores the `button` argument.

**Comment by YonKuma** [comment]
Got it. I'll get a change in tonight or tomorrow. As for the this.Button thing, it seemed weird but since it was consistent I figured it might be on purpose for some reason. Since I'm already hitting this method, I'll switch all the references over to button while I'm at it.

**Comment by Pathoschild** [comment]
The code also doesn't handle the other mouse buttons like middle-click. For completeness, we can replace this code:
```cs
// mouse
else if (button == SButton.MouseLeft)
{
    Game1.oldMouseState = new MouseState(
        Game1.oldMouseState.X,
        Game1.oldMouseState.Y,
        Game1.oldMouseState.ScrollWheelValue,
        ButtonState.Pressed,
        Game1.oldMouseState.MiddleButton,
        Game1.oldMouseState.RightButton,
        Game1.oldMouseState.XButton1,
        Game1.oldMouseState.XButton2
    );
}
else if (button == SButton.MouseRight)
{
    Game1.oldMouseState = new MouseState(
        Game1.oldMouseState.X,
        Game1.oldMouseState.Y,
        Game1.oldMouseState.ScrollWheelValue,
        Game1.oldMouseState.LeftButton,
        Game1.oldMouseState.MiddleButton,
        ButtonState.Pressed,
        Game1.oldMouseState.XButton1,
        Game1.oldMouseState.XButton2
    );
}
```
...with something like this:
```cs
// mouse
else if (button == SButton.MouseLeft || button == SButton.MouseMiddle || button == SButton.MouseRight || button == SButton.MouseX1 || button == SButton.MouseX2)
{
    Game1.oldMouseState = new MouseState(
        Game1.oldMouseState.X,
        Game1.oldMouseState.Y,
        Game1.oldMouseState.ScrollWheelValue,
        button == SButton.MouseLeft ? ButtonState.Pressed : Game1.oldMouseState.LeftButton,
        button == SButton.MouseMiddle ? ButtonState.Pressed : Game1.oldMouseState.MiddleButton,
        button == SButton.MouseRight ? ButtonState.Pressed : Game1.oldMouseState.RightButton,
        button == SButton.MouseX1 ? ButtonState.Pressed : Game1.oldMouseState.XButton1,
        button == SButton.MouseX2 ? ButtonState.Pressed : Game1.oldMouseState.XButton2
    );
}
```

I added this to the upcoming SMAPI 2.2 release. Feel free to leave the PR as-is if you want, and I'll make the change when I pull it.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 2.2 release. Thanks!

**Pull request merged**
