### PR TITLE
Allowing same-named assemblies to be loaded

### PR DESCRIPTION
**Pull request by Shockah**
Hey @Pathoschild. This PR makes it so same-named assemblies can be loaded multiple times. This means if two mods use two different versions of an assembly, they won't conflict anymore - each of them will use a different version of the assembly (unless they specify the same version, then only one will be loaded).

Tested it with AtraCore 0.1.0 specifically (uses outdated NuGet packages), latest SpriteMaster (uses same package AtraCore does, but newer) and latest Betwitched (from 2021). After the changes in this PR:
* AtraCore loads its own (older) version of Pintail - it used to get the latest from SMAPI instead.
* Both AtraCore and SpriteMaster load fine with their own dependencies, without issues - they used to fail and **crash** the game.
* Betwitched still gets rewritten and loaded fine.
* Edit-and-Continue when developing mods in Visual Studio is still working.

~~One more thing I have to look into is what if a mod hard references another mod's DLL, and then the referenced mod gets updated. I *think* that may currently fail with the code as-is, so I will be looking into it whether that's the case, and if so, looking into any possible changes to overcome this issue. Until then, I'll keep the PR as a draft.~~  
This is now handled.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks for the pull request!

I'm not opposed to the idea, but I see a few points for discussion:

* We used `Assembly.UnsafeLoadFrom` before this PR because otherwise .NET Framework could refuse to load downloaded DLLs (which all mods are). I'm not sure whether that's still an issue in .NET 5+, but it might be worth making this an experimental option until we're sure it works for all players.
* Could this cause state fragmentation, since each loaded version presumably has its own types? For example, let's say we have two versions of a framework mod: the version loaded by SMAPI, and an older version hard-referenced by another mod. When the other mod calls the framework mod's types directly, would that call a different API surface than the actual loaded mod (so e.g. it wouldn't update the real mod's state)? I'm not too worried about API calls through Pintail, but more so about mods which provide `static` APIs instead.
* Similarly, what are the consequences of using multiple versions of Harmony to patch the same code?
* We should test the performance/memory impact of loading every mod in its own assembly context, since we're trying to streamline performance in recent versions. This might also significantly impact performance and memory usage due to SMAPI rewriting & loading each referenced version separately (particularly on Android where SMAPI rewrites DLLs much more frequently).
* These warnings in the [MSDN docs](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext) might be relevant here:
  > Loading multiple copies or different versions of framework assemblies can lead to unexpected and hard-to-diagnose behavior.
  > ...
  > This can lead to confusing error messages, for example "Unable to cast object of type 'Sample.Plugin' to type 'Sample.Plugin'".

**Comment by atravita-mods** [comment]
> Could this cause state fragmentation, since each loaded version presumably has its own types? For example, let's say we have two versions of a framework mod: the version loaded by SMAPI, and an older version hard-referenced by another mod. When the other mod calls the framework mod's types directly, would that call a different API surface than the actual loaded mod (so e.g. it wouldn't update the real mod's state)? I'm not too worried about API calls through Pintail, but more so about mods which provide static APIs instead.

I think Bug Net + JA + any other JA mod would be a good test case here? But, also, like, does this affect core mods that manage internal state (I'm thinking spacecore recipes or any of atracore's caches).

**Comment by Shockah** [comment]
> otherwise .NET Framework could refuse to load downloaded DLLs

I'm not exactly sure how to trigger the quarantine thing to happen though. I assume I'd need someone else to build me *some* mod DLL, host it somewhere, download that and try to run it? While developing this PR, I've briefly tried using `Assembly.LoadFrom`, and all of the mods I had installed loaded just fine (even though in theory they came from the internet), so either the quarantine flag was already gone, or it wasn't needed in the first place. Anyway, unless we can reliably test this, I agree on this being experimental.

> Could this cause state fragmentation, since each loaded version presumably has its own types?
> Similarly, what are the consequences of using multiple versions of Harmony to patch the same code?
> But, also, like, does this affect core mods that manage internal state (I'm thinking spacecore recipes or any of atracore's caches).

Yeah, I believe static state would be a problem here. I think I could spend some more time on this PR to have two separate mechanisms - DLLs provided by mods would use the `FullName` treatment, while external ones (be it provided by .NET, Stardew, SMAPI or other mods) would get the current treatment. This approach could possibly even help with the problem I mentioned in the first comment.

> We should test the performance/memory impact of loading every mod in its own assembly context

This didn't seem to have any performance impact, but I didn't benchmark it (only going by "feel" here) nor test it with a lot of mods (only like 15, mostly frameworks and development stuff).

> These warnings in the [MSDN docs](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext) might be relevant here

Yeah, this is pretty clear though - we're loading the same (well, a different version, but still) assembly twice - types from assembly A 1.0.1 won't be compatible with types from assembly A 1.0.2. This *may* come up in some support issues later on, although Pintail should handle most of the cases where this would apply.

**Comment by atravita-mods** [comment]
> Yeah, this is pretty clear though - we're loading the same (well, a different version, but still) assembly twice - types from assembly A 1.0.1 won't be compatible with types from assembly A 1.0.2. This may come up in some support issues later on, although Pintail should handle most of the cases where this would apply.

this isn't released but a place where that might come up: atracore [has a data model](https://github.com/atravita-mods/StardewMods/blob/74c618df39c48d6e5a799a2b83707f08dfcb8e8a/AtraCore/AssetManager.cs#L43) it runs through the game's content system. Two [different](https://github.com/atravita-mods/StardewMods/blob/74c618df39c48d6e5a799a2b83707f08dfcb8e8a/PrismaticSlime/Framework/AssetManager.cs#L69) [mods of min](https://github.com/atravita-mods/StardewMods/blob/74c618df39c48d6e5a799a2b83707f08dfcb8e8a/MoreFertilizers/MoreFertilizers/Framework/AssetEditor.cs#L161)e then edit that asset, hard referencing atracore to use the model. What happens here?

**Comment by Shockah** [comment]
So apparently these are the steps to reproduce the quarantine attribute:

Create a file (I'll name it `Zone.txt` here) with the below contents:
```
[ZoneTransfer]
ZoneId=3
```

Modify an NTFS stream for the file you want to add the attribute to (I'll use `AtraCore.dll` here):
```
more Zone.txt > AtraCore.dll:Zone.Identifier
```

After this operation, checking the file properties does show up the usual "This file came from the internet" nonsense, but... I could still not reproduce it not loading when simply changing `Assembly.UnsafeLoadFrom` to `Assembly.LoadFrom` on my system, nor with the current state of the PR.

**Comment by Shockah** [comment]
Okay, I just pushed some changes that make it so assemblies are skipped by full assembly name if they're included with a mod, but by the short name (old behavior) otherwise. This should fix any potential issues I can *currently* think of. Tested it with the latest (unreleased) mods mentioned by @atravita-mods, no issues there; AtraCore 0.1.0 and SpriteMaster still work nice together too.

The only problem that I can think of is:
* Mod A has a NuGet Foo 1.0.1.
* Mod B has a NuGet Foo 1.0.2.
* Mod C depends on Mod A, and uses its Foo.
* Mod D depends on Mod B, and uses its Foo.
* A/C tries to pass Foo values around with B/D.

But I don't think that part is solvable.

**Comment by atravita-mods** [comment]
Shockah - just a quick question: are you using 7zip to unzip or the Windows/mac file built in unzipper? Because 7zip failing to set mark of the web correctly was a thing for the longest time.

....although that was apparently fixed in June of last year....

**Comment by Shockah** [comment]
Closing the PR, as it wasn't really a good approach to this problem, and my other PR #915 handles this much better.

**Pull request closed without merging**
