### PR TITLE
[Website] Cleanup log filtering a bit more, save state to URL

### PR DESCRIPTION
**Pull request by KhloeLeclair**
Hello, I'm back again!

As discussed in Discord, the message showing users how many messages there are in total was a bit unclear. I've updated the code to now count messages in collapsed sections, so the number of messages doesn't change regardless of if sections are collapsed or not. Additionally, it always uses the `showing X to Y of Z messages (total: Q)` format no matter if there are multiple pages or not.

Finally, and perhaps more important than the other changes, this also saves filter state into the URL so that people can link to a log with filtering already applied. Visible mods, log levels, and sections as well as filter text and flags are all saved to the URL along with the current page.

By default, URLs are left alone so you just have the usual `/log/d0bb9309c6ac4904a9387d1c3d569998` (as an example). Once users toggle a filter, that filter is added to the URL. Pagination parameters are also always added to the URL at that time.

For example, if a user filters the log to only show a few specific mods, they might end up with a URL like `/log/d0bb9309c6ac4904a9387d1c3d569998?Page=1&PerPage=1000&Mods=A0AAAAAAAAAAAAAAAAAAAAAAAAAA` where `Mods` is a base-64 encoded bitmap of enabled mods. Note that this particular example string is rather long because the log I'm testing with has 162 filterable mods.

Combine *all* the possible filters and you'd end up with a URL like `/log/d0bb9309c6ac4904a9387d1c3d569998?Page=1&PerPage=1000&Mods=A0AAAAAAAAAAAAAAAAAAAAAAAAAA&Levels=fQ--&Filter=test&FilterMode=AQ--`  as a worst case scenario.

Parameters are only added if the user's filter state does not match the default filter state of the page.

### CODE REVIEW

**Comment by Pathoschild** [comment]
This is a pretty interesting approach, but I don't like adding 150+ lines of code to store a few URL parameters. I'm also not sure it's needed here, since...

* mod IDs and levels are restricted to URL-safe values;
* users will only choose a few mods (since they need to tick each box one at a time);
* and the URL limit is pretty big anyway.

So we could simplify all this code and just store a plain list of enabled mod IDs. For example, if the log has 1000 mods installed with three selected:
```
// current
&Mods=4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

// proposed
&Mods=Pathoschild.Automate,Pathoschild.ContentPatcher,spacechase0.JsonAssets
```

That has the advantage of being easy to read and hand-edit, so we can do things like just append the mod IDs we want to see at the end of any log URL.

**Comment by KhloeLeclair** [comment]
Looking at it later, I think you're right. I was probably over-engineering it for a scenario that's unlikely to come up in practical usage. I'll update the code to use a readable list instead.

**Comment by KhloeLeclair** [comment]
Alright, I've switched to using separated strings. Not using mod UniqueIDs, since those aren't known(?) or used by the filter, but the slugs instead. Example URL:
```
/log/d0bb9309c6ac4904a9387d1c3d569998?Page=1&PerPage=1000&Mods=game~SMAPI&Levels=error~alert~critical&Filter=test&FilterMode=Sensitive
```

As a side note, should the server be stripping `critical` from the list of levels passed to the client since there's no button for selecting it? Or should there be special logic to avoid including it in the URL?

You'll note I'm using `~` as a separator character rather than a comma. That is because commas are reserved characters in URLs and cannot be used in query parameters without being encoded. According to the RFC, unreserved characters are:
```
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```
Commas could still be used, but they'd be URL encoded into `%2C` which slightly defeats the point if going for readability. We could use anything, but tilde seemed to me the least likely to collide with possible values.

Additionally, I added a set of scrolling links to the left sidebar, which stay fixed to the bottom corner. Screenshot:

image

I've gotten a bit tired of scrolling past very large mod lists to get to the log itself, and this was my solution. It still needs work before going live (in the event of horizontal scrolling), but I thought I'd include it here to see what you think.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks again! Merged into `develop` and deployed.

The `critical` log level isn't listed in the filters since it's rare and easy to find in the log, but I don't think we need any special handling for it otherwise.

**Pull request merged**
