### PR TITLE
Installer looks for more paths, also saves last user picked one

### PR DESCRIPTION
**Pull request by InkyQuill**
I was frustrated of installer asking me for a path every single time I try to update SMAPI. My setup is a Steam folder copied from another computer, so it has no install info for Stardew Valley. Rewrote logic a bit to allow finding folder through Steam path (getting Steam install path from HKCU), also saving user-chosen path to HKCU and getting it on subsequent installs. Also, rebuilt path checking logic a bit to ensure that user is not presented with duplicate paths.

### CODE REVIEW

**Comment by chaos234** [comment]
This is a nice idea but what will happen if I moe the game to another location containing SMAPI in it. Will it be moved too? If so, then the last stored path wouldn't work anymore, am I rigth and if so, is this coverable eventually?

**Comment by InkyQuill** [comment]
Good question. The procedure is simple, installer checks for already set paths, if it can't find any game in there, it should ask again.
I can propose one solution which won't require setting an update path again. We can give the main SMAPI process an ability to store its own path in windows registry on launch. Then it will be checked in installer on subsequent installs. But this means you'll need to run SMAPI in moved folder at least once. Should I implement this solution? This also can be implemented to allow multiple installs (even with different versions) on one system.

**Comment by chaos234** [comment]
Sounds nice and I think implementing it shouldn't hurt since it is a nice enhancement at the end :) - So yes, I would like it if u can implement it.

**Comment by InkyQuill** [comment]
But this also means that we'll need a confirmation on installation, if automatically discovered path should be used or some user-chosen one.

**Comment by InkyQuill** [comment]
I'll see into it, it shouldn't be hard, just some small enhancements.

**Comment by InkyQuill** [comment]
Should be all that was planned.
For now, this PR changes the following:
- Adds a routine for SMAPI to add its install path into Windows Registry (maybe allow it for all platforms? Mono has its own implementation of Registry on Linux/Mac)
- Adds an ability for user to set their own path even if auto-discovery returns a path. 
- Adds user-selected path into Registry on installation.

**Comment by Pathoschild** [comment]
Thanks for the pull request! Smaller pull requests are usually best so they can be considered independently though. I'd merge the Steam folder check right away, but I'm not sure yet about the installer storing previous paths in the registry. I'll keep this open and take another look for an upcoming 2.6 beta. :)

**Comment by Pathoschild** [comment]
I manually merged the Steam library path and anti-duplicate logic into `develop` for the upcoming SMAPI 2.6-beta.16.

All that's left for this PR is saving paths to the registry. SMAPI is a portable app, and I'm not sure how I feel about storing global state in the registry even if it's optional.

**Comment by Pathoschild** [comment]
Most of the changes were merged into SMAPI 2.6.

Since SMAPI already has a [standard file to override the game path](https://github.com/Pathoschild/SMAPI/blob/develop/docs/mod-build-config.md#game-path), I don't think it makes sense to introduce a new one in the registry. It could be useful to optionally save the custom path to that file instead, but that'd be a separate pull request.

Thanks for the contribution!

**Pull request closed without merging**
