### PR TITLE
Improve performance of PrivateProperty

### PR DESCRIPTION
**Pull request by Entoarox**
This PR will take advantage of the way C# delegates are implemented to improve performance of Getting or Setting properties using the `PrivateProperty` reflection helper.

Included is also C#7 changes to the file as recommended by VS.

### CODE REVIEW

**Comment by Pathoschild** [comment]
These changes crash SMAPI with this error:
```
[12:45:26 ERROR SMAPI] An error occured in the overridden draw loop: System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, MethodInfo method)
   at StardewModdingAPI.Framework.Reflection.PrivateProperty`1..ctor(Type parentType, Object obj, PropertyInfo property, Boolean isStatic) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\PrivateProperty.cs:line 54
   at StardewModdingAPI.Framework.Reflection.Reflector.GetPropertyFromHierarchy[TValue](Type type, Object obj, String name, BindingFlags bindingFlags) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\Reflector.cs:line 207
   at StardewModdingAPI.Framework.Reflection.Reflector.GetPrivateProperty[TValue](Object obj, String name, Boolean required) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\Reflector.cs:line 76
   at StardewModdingAPI.Framework.SGame.get_screenWrapper() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 145
   at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 671
   at StardewModdingAPI.Framework.SGame.Draw(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 597
```

**Comment by Entoarox** [comment]
The second commit should have fixed everything pathos, I at least did not run into any issues with these changes during my testing, so if there are any, it is likely to be a edge-case situation between the behaviour of `GetValue/SetValue` and using delegates to directly call the `get_<name>/set_<name>` methods.

**Comment by Pathoschild** [comment]
Thanks! I slotted this into the 2.1 release, so I'll review it soon.

**Comment by Pathoschild** [comment]
@Entoarox Your latest changes crash with this error when loading a save that has a non-default zoom level:
```
An error occured in the overridden draw loop: System.InvalidCastException: Unable to cast object of type 'System.Func`2[StardewValley.Game1,Microsoft.Xna.Framework.Graphics.RenderTarget2D]' to type 'System.Func`2[System.Object,Microsoft.Xna.Framework.Graphics.RenderTarget2D]'.
   at StardewModdingAPI.Framework.Reflection.PrivateProperty`1..ctor(Type parentType, Object obj, PropertyInfo property, Boolean isStatic) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\PrivateProperty.cs:line 56
   at StardewModdingAPI.Framework.Reflection.Reflector.GetPropertyFromHierarchy[TValue](Type type, Object obj, String name, BindingFlags bindingFlags) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\Reflector.cs:line 207
   at StardewModdingAPI.Framework.Reflection.Reflector.GetPrivateProperty[TValue](Object obj, String name, Boolean required) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\Reflector.cs:line 76
   at StardewModdingAPI.Framework.SGame.get_screenWrapper() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 145
   at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 671
   at StardewModdingAPI.Framework.SGame.Draw(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 597
```

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 2.1 release. Thanks!

**Pull request closed without merging**
