### PR TITLE
Experimental Android support

### PR DESCRIPTION
**Pull request by ZaneYork**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! This is an interesting approach, but I prefer not changing the game executable or recreating each mod. Instead of patching the game to call SMAPI, would this approach (similar to other platforms) work on Android?

1. When the user launches the game, it runs the SMAPI executable instead of the game executable;
2. SMAPI loads the game, adds mods, and launches the game as a subprocess.

This has the benefit of being easier to install (don't need to change the game executable itself), and in theory other mods could be added as-is without reimplementing each one.

**Comment by ZaneYork** [comment]
Good idea.But this strategy needs a Android Application to grab Dlls from Stardew Valley and delegate it.However,if user does not have root access, the Application should extract Contents from apk file.
I will improve this branch later, so that mod developer don't have to transportation mods.

**Comment by alightbullb** [comment]
Any idea how soon this could be playable? Thanks so much for the hard work btw!

**Comment by Pathoschild** [comment]
@alightbullb You can [try it already](https://www.reddit.com/r/StardewValley/comments/bbou7m/zaneyorks_mod_loader_for_android_supports_content/). It's still experimental and unofficial though, so expect bugs, issues, and most mods outright not working yet.

**Comment by Pathoschild** [comment]
@ZaneYork Thanks for all your work! Unfortunately this pull request can't be merged for two reasons:

* It removes support for players on Linux/Mac/Windows and removes most of the internal code. Ideally the main repository should support all platforms, using conditional compilation where necessary to account for crossplatform differences. At a minimum, the main repository should support Linux/Mac/Windows since those are the main and original platforms.
* It includes the source code for several mods without complying with their code licenses. Some of those mods have incompatible licenses or are fully copyrighted, so redistributing their code without permission is a copyright violation.

As such I'll close this pull request. Feel free to submit a new pull request when those are addressed, or maintain a SMAPI fork for Android! You can discuss progress in the tracking ticket (#632), which I'll also update with a link to your repository.

**Pull request closed without merging**
