### PR TITLE
Added Font loading to the ModContentManager

### PR DESCRIPTION
**Pull request by Platonymous**
Allows this to work:
```
SpriteFont spriteFont = Helper.Content.Load<SpriteFont>(assetNameSpriteFont);
FontFile fontFile = Helper.Content.Load<FontFile>(assetNameFontFile);
List<Texture2D> fontFilePages = 
fontFile.Pages
.Select(p => Helper.Content.Load<Texture2D>(p.File, ContentSource.GameContent))
.ToList();
```
The game loads it's FontFile pages like this:
```
foreach (FontPage page in SpriteText.FontFile.Pages)
           SpriteText.fontPages.Add(Game1.content.Load<Texture2D>(string.Concat("Fonts\\", page.File)));
```
So it is to be noted that should this be used to replace vanilla fonts, the extra "Fonts" directory would need to be accounted for, which this does not.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks for the PR! The font parsing logic is out of scope for SMAPI itself though; ideally it would be encapsulated into an external package like we do for TMXTile. Also, while loading custom fonts from the mod folder is interesting, I think replacing vanilla fonts would be the most common use case that we'd want to support for SMAPI (e.g. for CP content packs).

**Comment by Platonymous** [comment]
The last change accounts for vanilla files replaced with CP.
What modders would have to do in cp is:
```
{  
      "Action": "Load",
      "Target": "Fonts/Russian",
      "FromFile": "fonts/NewRussian.fnt"
	},
	{
      "Action": "Load",
      "Target": "Fonts/Russian_0",
      "FromFile": "fonts/NewRussian_0.png"
}
```
For SpriteFonts this would be enough:
```
{  
      "Action": "Load",
      "Target": "Fonts/SpriteFont1",
      "FromFile": "fonts/NewSpriteFont.json"
}
```

**Comment by avxit** [comment]
Hi, any progress on this PR? I'm translating the game into my native language (Vietnamese) but these original fonts doesn't support some character. I don't want to replace any original game file with modified one, so this PR is a big help. Hope it would be merged soon. Thanks!

**Comment by Pathoschild** [comment]
@avxit Hi! You don't need this PR to have custom fonts. You can pack the font into an `.xnb` file, and load it through `Action: Load` (via Content Patcher) or `IAssetLoader` (via SMAPI). Feel free to ask in [#making-mods on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) if you need any help with that; I think one of the mod authors there did that recently.

(This PR adds a way to load _unpacked_ font files, but I'm not sure whether I want to use this approach; I'd prefer to avoid font parsing logic and conventional filename matching in the SMAPI core.)

**Comment by avxit** [comment]
> @avxit Hi! You don't need this PR to have custom fonts. You can pack the font into an `.xnb` file, and load it through `Action: Load` (via Content Patcher) or `IAssetLoader` (via SMAPI). Feel free to ask in [#making-mods on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) if you need any help with that; I think one of the mod authors there did that recently.

Yes, I've tried this way. But my mistake is using old version of `xnb-cli` to unpack/pack fonts and got broken assets. The game crash when trying to load it. And when I try to use `StardewXnbHack` to unpack then `xnb-cli` can't repack because JSON format isn't correct. So I came to this PR for a solution. Now with updated `xnb-cli` everything seem to be worked.

> (This PR adds a way to load _unpacked_ font files, but I'm not sure whether I want to use this approach; I'd prefer to avoid font parsing logic and conventional filename matching in the SMAPI core.)

 Thank you for clarifying this. But if SMAPI could provide a way to load unpacked fonts is so great. For example, kerning custom font the way I do now is so frustrating (edit custom format JSON from `xnb-cli` is 😵) but with JSON unpacked from `StardewXnbHack` is pretty easy to read and edit.

**Comment by Pathoschild** [comment]
SMAPI 3.13.0 added support for custom BmFont assets in a simpler way to support custom languages; see [Modding:Custom languages#Add a custom font](https://stardewvalleywiki.com/Modding:Custom_languages#Add_a_custom_font) on the wiki for more info. Thanks for the PR though!

**Pull request closed without merging**
