### PR TITLE
Improve log parser

### PR DESCRIPTION
**Pull request by KhloeLeclair**
Hello!

This pull request overhauls the website's log parser to improve performance and usability.

Previously, the log was rendered server-side and then used as a template by a Vue application on the client in order to perform filtering. This is not great for performance, particularly for large logs. I got started on this after a user on Discord linked a log that was long enough to crash the browser tab while eating over 8GB of RAM, despite only being a 22MB log file.

To address the problem, I've removed the server-side rendering of the log. Users without JavaScript enabled can still view the raw log, so I don't see this as an issue. Instead, the server emits a JSON array with all the messages that the client parses and loads. I freeze every message object to prevent Vue from doing unnecessary instrumentation to watch for changes. I make use of Vue's computed values system to filter the list of messages, and then that list is rendered using functional components.

Further, I've added pagination to limit the number of drawn lines. I experimented with the use of a virtual list, but didn't like how the scrolling performed within the page layout. It might be something to revisit in the future.

While I was digging around, I also implemented a text input filter with support for regular expressions. This feature highlights text in log lines (by default, though it can be disabled by users in case it's slow for them).

Other misc tweaks:
* The filters bar is now sticky, staying at the top of the screen when scrolling past it.
* There is now a button to toggle the display of Content Packs in the mod list, since they can take up a lot of space when we might not actually care about the details.

I've tested this semi-thoroughly, though it's difficult given the lack of a proper JavaScript environment for SMAPI's website. Testing included using this on my phone (OnePlus 9) and it worked well there.

Screenshot demonstrating pagination, filtering, highlights, and the sticky filter bar:
image

### CODE REVIEW

**Comment by KhloeLeclair** [comment]
Hello! So I'm watching this and noticed that you changed the code to pass the JSON directly into the main `<script>` tag. This is, frankly, not a good thing and can cause the page to take seconds longer to load for larger log files.

When the browser is loading a page, it parses all JavaScript included in `<script>` tags and executes them synchronously. Now, because you're injecting multiple megabytes of JSON into a script tag, the browser is forced to sit there and parse megabytes of JSON... as JavaScript.

As it's in a plain script tag, the browser has no idea that it's a strict JSON document and has to parse it as though it's JavaScript, which is slower. In quick testing on my machine, these changes make just script tag parsing take about a full second longer according to Lighthouse.

When I used a `<script type="application/json">` tag to store the data, the browser does *not* parse the text as anything when doing the initial page load. We can then, at our leisure, use `JSON.parse()` to parse it which is both more secure than normal JS parsing, and also quite a bit more efficient.

Metrics from Chrome's Lighthouse performance testing tool, comparing the two approaches:

<table>
<thead>
<tr><th>Metric</th><th>Separate Tag</th><th>Embedded JSON</th></tr>
</thead>
<tbody>
<tr><td>First Paint -> Interactive</td><td>5.9 seconds</td><td>15.2 seconds</td></tr>
<tr><td>Total Blocking Time</td><td>5,070ms</td><td>13,720ms</td></tr>
<tr><td>Main Thread Work</td><td>11.1 seconds</td><td>18.9 seconds</td></tr>
<tr><td>- Script Parsing</td><td>201ms</td><td>1,326ms</td></tr>
<tr><td>- Script Evaluation</td><td>3,018ms</td><td>8,702ms</td></tr>
<tr><td>- Garbage Collection<td>210ms</td><td>516ms</td></tr>
</tbody>
</table>

You can find attached the two lighthouse reports I pulled those numbers from. I did run each test several times and received similar results: [Reports.zip](https://github.com/Pathoschild/SMAPI/files/8457569/Reports.zip)

Just to note, this is with Lighthouse in mobile device mode to simulate the performance of mobile devices. I like to use that when performance testing to make it easier to spot performance issues. In desktop mode it's more like 2 seconds vs 4 seconds, with 890ms of blocking time vs 3,060ms on my 5900X. Still not ideal.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
All done. I restored loading the data from JSON, though I merged them into one block and passed the ID into the script instead of hardcoding it. Any objections or improvements for the new code?

**Comment by KhloeLeclair** [comment]
It looks good to me. Performs about the same on my machine.

**Comment by Pathoschild** [comment]
Merged into `develop` and deployed. Thanks for the changes!

**Pull request merged**
