### PR TITLE
Add chest items changed event

### PR DESCRIPTION
**Pull request by wartech0**
### **Implementation Description**
Added ChestItemChanged event, this feature will add the ability for mod developers to check what items are being put into a chest and an event will fire when done so. The event arguments provide the items added and removed as well as the location of the chest.
### 
### **Current Known Issues**
As for right now when a stack change occurs NetListWatcher doesn't get the ElementChanged event fired off, if this ever changes code has been added (but commented out) to compare items to determine if the stack size has changed.

### CODE REVIEW

**Review by Pathoschild — CHANGES_REQUESTED** [review]
Thanks!

A few requested changes:
* [x] the event arguments should include the `Chest` that changed;
* [x] the event shouldn't be raised for reordered items (similar to `PlayerEvents.InventoryChanged`);
* [x] the event should track stack size changes (also similar to `PlayerEvents.InventoryChanged`);
* [x] when handling `NetList.OnArrayReplaced`, items which haven't changed since the last update shouldn't be treated as changes (probably the same code to fix reordering above would address this).

Note that I committed some changes to your branch, so you should pull before making any further changes.

**Comment by wartech0** [comment]
Thanks, I will review and work on requested changes.

**Review by wartech0 — COMMENTED** [review]
Requested changes have been made and I cleaned up the chest handling code significantly

**Comment by Pathoschild** [comment]
(Rebuilt the branch without the various merge commits.)

**Review by Pathoschild — CHANGES_REQUESTED** [review]
Thanks! A few notes on the new changes:
* [x] We shouldn't recopy the inventory for every chest each tick; it's much more efficient to use the underlying events (like in your previous implementation) to update the list, then we just need to check for changed stack sizes.
* [x] `ChestTracker` should be `IDisposable` and disposed when it's no longer needed, so it can release item references and event handlers.
* [x] In `LocationSnapshot.Update`, if a chest is removed the previous changes are no longer removed from the snapshot.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 3.1. Thanks for the contributions!

**Pull request merged**
