### PR TITLE
Fix assembly rewriting causing VS to error/crash when debugging

### PR DESCRIPTION
**Pull request by spacechase0**
This does however leave out line numbers from the rewritten DLLs, but I believe they didn't have them before anyways.

~~If for some reason your main DLL (for the mod you are developing) is rewritten, breakpoints set through the IDE won't trigger. You can still set one using `System.Diagnostics.Debugger.Break()`. It might not show the place in your file though.~~ I think this was actually due to a bug I've since fixed (not using the newly written PDB), since it is working now for me.

### CODE REVIEW

**Comment by spacechase0** [comment]
This isn't quite ready yet, actually. Some assemblies use the portable format for PDBs, while some use the normal windows format. The ISymbolReader provided can't read both, and so errors on mods with the wrong type. (I swapped which one it used and it swapped which mods errored.)

**Comment by spacechase0** [comment]
I'll do some cleanup/documenting/rename MySymbolReader tomorrow.

**Comment by Pathoschild** [comment]
Rebased from SMAPI 3.13.0-beta into the upcoming SMAPI 3.12.3.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming SMAPI 3.12.3.

**Pull request merged**
