### PR TITLE
Rewrite asset name comparison to stop at the first mismatch

### PR DESCRIPTION
**Pull request by atravita-mods**
Hi Pathos!

This PR just makes `AssetName.IsEquivalentTo` and `AssetName.StartsWith` avoid splitting + re-forming strings all the time. Instead, it now checks each segment of each path against the matching segment in the other path.

Couple of things I should probably apologize for:
1. I just stuck AssetPartYielder in a random namespace, I don't really know where it should go best.
2. I hope the comments made sense. I tried to insert comments where it made sense, but let me know if anything's unclear.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks for the pull request! This adds a bit of complexity, and I'm not sure about the performance impact of using enumerators compared to the previous eager normalization since this is a hot path. Any chance you could run some [Benchmark.NET](https://benchmarkdotnet.org/) tests to compare runtimes and memory allocation between the old & new implementations?

**Comment by atravita-mods** [comment]
I'm not sure the enumerator will have much of an impact. It's not a real enumerator, it's a ref struct pretending to be one.

For a quick "realistic" test case, I took one single mass invalidation - 67 asset names - and compared to a single asset. 

image

(will work on better ones later).

**Comment by atravita-mods** [comment]
image

Okay, benchmarks in. I did three.

The first, I just copied a pile of asset names from a single asset invalidation event, so 67 assets in all, one which matched. (and thus about 67x slower than the other two). The others are simple match/didn't match. Of each, the new implementation is first, the previous one is second. 

Couple of notes: the realistic test is a less-that-ideal case - the first segment matches for about half of the test cases, while realistically very often the first segment is enough to reject. 

(actual code: https://gist.github.com/atravita-mods/5322e2b42fdaa23700d1c0d1cbcd9add )

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 3.18,.0. Thanks for the help!

**Pull request merged**
