### PR TITLE
Adding a date function

### PR DESCRIPTION
**Pull request by Sakorona**
This adds a date function that is a way to get an absolute reference.

### CODE REVIEW

**Comment by Pathoschild** [comment]
@JohnsonNicholas You added a static method that takes an `SDate` as input and returns the number of days since 0 spring Y1. That works fine, but it can be improved a bit: the SMAPI APIs generally avoid static members and this one needs an input date anyway; the existing `GetHashCode` method returns the same value; and that value is used in several calculations and doesn't change after the date is constructed.

Per the above, I suggest...
1. Create a private `GetDaysSinceStart` method containing the logic of `GetHashCode`.
2. Replace the `TotalNumberOfDays` method with this property:
   ```cs
   /// <summary>The number of days since the game began (starting at 1 for the first day of spring in Y1).</summary>
   public int DaysSinceStart { get; }
   ```
   ...and initialise it in the internal `SDate` constructor:
   ```cs
   this.DaysSinceStart = this.GetDaysSinceStart();
   ```
3. Change `GetHashCode()` to return `this.DaysSinceStart`.
4. Change date calculations to use `DaysSinceStart` instead of `GetHashCode()` where appropriate.

I added this ticket to the upcoming SMAPI 2.2 release. Feel free to leave the PR as-is if you want, and I'll make those changes when I pull it.

**Comment by Sakorona** [comment]
The goal was to be able to call it for any arbitrary date, which is why it was a static call. I can see the value of the syntactic sugar call of 

`public int DaysSinceStart => SDate.TotalNumberOfDays(this)`
 
but it's more .. generally useful for it not to be called by the constructor. 

Something like SDate should probably have some static members since date calculations like that aren't precisely unknown and it beats creating something like `new SDate(2, "spring", 1).DaysSinceStart` (in my view) just to poll how many days it's been. That said, I suppose I could convert it over. I just don't think it's a good idea to not have the ability to call it for an arbitrary date. (Although I think this is definitely a style thing, I generally avoid recreating objects as much as I can.)

**Comment by Pathoschild** [comment]
The static method needs an `SDate` passed in anyway, though. I don't see any case where the static method is simpler:
```cs
// with static method
SDate date = new SDate(2, "spring", 1);
int days = SDate.TotalNumberOfDays(date);

// with instance property
SDate date = new SDate(2, "spring", 1);
int days = date.DaysSinceStart;
```

**Comment by Sakorona** [comment]
Valid point. I'll push a commit when I get home.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming SMAPI 2.2 release. Thanks!

**Pull request merged**
