### PR TITLE
Fixed a game crash

### PR DESCRIPTION
**Pull request by f4iTh**
Sample log: https://log.smapi.io/0MsvjBZA

### CODE REVIEW

**Comment by ghost** [comment]
I have the same problem :(

**Review by reveriadive — CHANGES_REQUESTED** [review]
Change all of the ForEquatable to ForReference here with those edits, and it fixes the issues from Stardew's update entirely.

**Comment by ghost** [comment]
I don't understand what I have to do :/

**Comment by Hammster** [comment]
@Beatriizcsantos you don't have to do a thing this here is a code fix. Once the new version is out you can get it like you normally do.

**Comment by Pathoschild** [comment]
Thanks for the pull request! Now that the skills are net fields, we can use the more efficient `NetValueWatcher` instead of `EquatableWatcher`. I'll close this and make those changes as part of #521. :)

**Pull request closed without merging**
